name: Update Badges

on:
  workflow_dispatch: # Allow manual runs

jobs:
  update-badges:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: zen-aufa-bahalwan # Uses your GitHub username
          NUMBER_LAST_BADGES: 0 # Show last 10 badges (0 = all)
